project:
  type: book
  output-dir: _book

python:
  executable: .venv/bin/python

book:
  title: "Limits of AI peer review on real expert review data"
  author:
    - name: "Valentin Klotzbücher"
      orcid: 0000-0001-9382-6757
      email: valentin.klotzbuecher@usb.ch
      affiliation: "University of Basel & University Hospital Basel"
    - name: "David Reinstein"
      affiliation: "The Unjournal"
      # email: davidreinstein@unjournal.org
      orcid: 0000-0002-0470-4991
    - name: "Lorenzo Pacchiardi"
      orcid: 0000-0003-4760-7638
      # email: lo
      affiliation: "University of Cambridge, Leverhulme Centre for the Future of Intelligence"
    - name: "Tianmai Michael Zhang"
      orcid: 0000-0001-5108-9250
      email: tianmai@uw.edu
      affiliation: "University of Washington"
    # - name: "Casey Wimsatt"
    # - name: "Lorenzo Pacchiardi"
  chapters:
    - index.qmd
    - results.qmd
    - discussion.qmd
    - methods.qmd
    - references.qmd
  appendices:
    - results_ratings.qmd
    - results_critiques.qmd
    - appendix_llm_traces.qmd
  date: last-modified
  abstract: |
    We benchmark how frontier LLMs critique, rate, and prioritize research, comparing AI-generated evaluations to human expert assessments from The Unjournal. Human ratings serve as a reference signal—the core goal is measuring and diagnosing AI reasoning quality: understanding calibration, failure modes, and systematic "taste" differences between AI and human evaluators.
  repo-url: https://github.com/valentinklotzbuecher/llm-uj-research-eval
  downloads: [pdf]
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: rocket
        href: https://www.unjournal.org/
        text: "The Unjournal"
      # - icon: display
      #   href: slidesvk.html
      #   text: "📊 Slides"

bibliography:
  - "references.bib"
csl: "the-quarterly-journal-of-economics.csl"
link-citations: true


format:
  html:
    theme:
      dark: [darkly, theme-dark.scss]
      light: [journal, theme-light.scss]
    mainfont: Inter
    googlefonts:
      - Inter:400,400i,500,600,700
    highlight-style: atom-one
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    smooth-scroll: true
    code-fold: true
    code-tools: true
    code-summary: "Show code"
    code-overflow: wrap
    fig-cap-location: bottom
    fig-align: left
    df-print: paged
    execute:
      warning: false
      message: false
      freeze: false
      cache: false
      python: "python3"
  pdf:
    documentclass: article
    top-level-division: section
    fontsize: 11pt
    geometry:
      - margin=1in
      - headheight=14pt
    toc: false
    number-sections: false
    include-in-header: preamble.tex
    link-citations: true
    keep-tex: true
    fig-cap-location: top
    fig-align: left
    df-print: kable
    pdf-engine: xelatex
    execute:
      warning: false
      message: false
      freeze: auto
      cache: true
      prefer-html: true
      echo: false
