project:
  type: book

book:
  title: "Comparing LLM-Generated Reviews to Human Evaluations in Social Science Research"
  author:
    - name: "David Reinstein"
      # affiliation: "The Unjournal"
    # - name: "Alexander Herwix"
    - name: "Valentin Klotzb&uuml;cher"
      orcid: 0000-0001-9382-6757
      email: valentin.klotzbuecher@econ.uni-freiburg.de
      # affiliation: "University of Freiburg"
    # - name: "Emmanuel Orkoh"
    # - name: "Lorenzo Pacchiardi"
    # - name: "Casey Wimsatt"
  chapters:
    - index.qmd
    - numerical_ratings.qmd
    # - journal_rankings.qmd
    # - claim_identification.qmd
    # - llm_evals.qmd
    # - human_evals.qmd
    # - compare_evals.qmd
    - references.qmd
  date: last-modified
 
bibliography: 
  - "references.bib"
csl: "the-quarterly-journal-of-economics.csl"
link-citations: true


format:
  html:
    theme: [journal, theme-light.scss]
    # googlefonts:
    #   - Source Sans Pro:400,600
    highlight-style: atom-one
    toc: true
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    callout-appearance: minimal
    embed-resources: true
    smooth-scroll: true
    code-fold: true
    code-tools: true
    code-summary: "Show code"
    code-overflow: wrap
    fig-cap-location: top
    fig-align: left
    lightbox: true
    df-print: paged
    execute: 
      warning: false
      message: false
      freeze: auto
      cache: true
    code-links:
      - text: Project files
        icon: github
        href: https://github.com/valentinklotzbuecher/llm-uj-research-eval
    other-links: 
      - text: The Unjournal
        icon: rocket
        href: https://www.unjournal.org/
      - text: Shared notes
        icon: google
        href: https://docs.google.com/document/d/1F9bDUh1UuayQsPG2PpylwbPfDs5a-bRCOt1F-q2Qv5A/edit?usp=sharing
        
 