name: qpy311
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - pip
  - jupyter
  - nbformat
  - ipykernel
  - jupyter-cache
  - numpy
  - pandas
  - matplotlib
  - scipy
  - altair
  - plotly
  - ipython
  - tqdm
  - pdfplumber
  - tiktoken
  - openai
